services:
  - type: web
    name: mediconnect
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mediconnect-db
          property: connectionString

databases:
  - name: mediconnect-db
    engine: postgres
    version: "15"
    plan: starter
    initialDbName: mediconnect
    ipWhitelistItems: []